### ISSUE TITLE
Navbar & Landing Page

### ISSUE THREAD

**Issue by codeza-ai** [satyam8932/genieai#18]
I would like to work on the Navbar and the Landing page. It seems it is incomplete yet. I would like to add responsiveness and good styling to the navbar component. Also the Landing page is a little empty, I would like to add a bit description to it. Please assign me the issue and add appropriate tags to the issue.

**Comment by codeza-ai** [comment]
Please add some issues to work on, meanwhile I will also try to find any features that I can add.

**Comment by satyam8932** [comment]
Ok bro, here's what you can do

**Comment by satyam8932** [comment]
Ok, here's what you can do

If you go to the genieai website and go to dashboard there will be three tools listed DocBot works fine but for ArtSynth i need some improvements 

Make the images downloadable using a download button
Add a image skeleton to show it while loading the image ( i think skeleton is already there but still it gets disappear and image takes time to render) so please fix these two things and if i wil like you work then i will assign more to you

Also please make sure that you follow standard coding practise production grade with proper comments and documentation as it's important so that other users can understand what has been done

Let me know if you are ready then i will assign you this issue.

Thanks
Satyam

**Comment by codeza-ai** [comment]
@satyam8932 Thanks alot. I am a newbie to open source contributions, so I am still learning. I will try my best.

**Comment by satyam8932** [comment]
@codeza-ai Goodluck I'm assigning this issue to u.

**Comment by codeza-ai** [comment]
@satyam8932 Is there any way to communicate with you ? I have some doubts.

**Comment by satyam8932** [comment]
***@***.***

or also via linkedin
link is in profile

**Comment by Balamurugan-cyber** [comment]
please assign this issue

**Comment by satyam8932** [comment]
@Balamurugan-cyber this issue is already been assigned to @codeza-ai

**Comment by satyam8932** [comment]
Due to no contributions and PR's this issues has been closed.
